### ISSUE TITLE
Set up GitHub/Circle/AWS pipeline with secrets

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#19]

**Comment by alexwlchan** [comment]
My current thinking is something like:

1. Push to master on GitHub
2. Circle CI builds a container, pushes to Docker Hub
3. An AWS Lambda picks up the container, bakes in the secret config, pushes to ECR
4. A second Lambda picks up the container from ECR

(1) is trivial, we already have most of (2), I’m working on (3) and (4) today.

**Comment by alexwlchan** [comment]
> An AWS Lambda picks up the container, bakes in the secret config, pushes to ECR

Question I didn’t immediately realise the implications of: how do you build a Docker container in a Lambda?

**Comment by kenoir** [comment]
Circle can do both build steps, and the Terraform plan, however the apply
should be done inside AWS to remove the need for explicit credentials with
the ability to perform significant infra changes.

On Thu, Feb 2, 2017, 9:10 AM Alex Chan <notifications@github.com> wrote:

An AWS Lambda picks up the container, bakes in the secret config, pushes to
ECR

Question I didn’t immediately realise the implications of: how do you build
a Docker container in a Lambda?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wellcometrust/platform-api/issues/19#issuecomment-276904173>,
or mute the thread

**Comment by alexwlchan** [comment]
We’re now doing our `terraform apply` in AWS rather than Lambda, and the script for that is here: https://github.com/wellcometrust/terraform-lambda/pull/1

**Comment by kenoir** [comment]
Closing for now as we will revisit when we have more pressing cause.
