### ISSUE TITLE
Agree approach to identifiers

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#31]

**Comment by alexwlchan** [comment]
Copying some notes from a conversation with @kenoir:

Our identifier service needs to solve a couple of problems:

* **Uniqueness.** Because we have multiple data sources allocating their own identifiers, there might be records from two sources which have the same internal ID, but which refer to different items.
* **Merging.** Records in different data sources with different IDs might refer to the same item – we need to be able to tie these together under the same ID in the new system.
* **Deterministic.** Given a record, we need to be able to check if there’s already an allocated ID (so we can update it rather than create a new record).

Our current idea looks something like this:

<img width="599" alt="identifiers" src="https://cloud.githubusercontent.com/assets/301220/23792614/9862a95c-057f-11e7-92c2-88951168f7d7.png">

Records within each data source are as follows:

```
record:
    - primary_id
    - identifiers
        - alt_id_1
        - alt_id_2
        - ...
```

where we might want to correlate `identifiers` across multiple data sources.

So when the transformer processes a record, it asks an ID service _“I have this primary ID X and identifiers Y from data source Z, do you have a canonical ID?”_ The ID service checks our Elasticsearch index for matching records:

* If one exists, you return it
* If it doesn’t exist, you create one from scratch _and create a stub record for it in Elasticsearch_. This is to prevent race conditions – e.g. if a record for an item is created in Sierra and Calm on the same day, we don’t want the ingestors to create two distinct IDs. This stub record should be unsearchable through the public API.

How those identifiers are allocated remains an open problem.

**Comment by jtweed** [comment]
Are we sure it's a good idea to rely on Elasticsearch here? Is it not safer to use DynamoDB for the ID service?

We may have multiple ES indexes, they may be out of date, it's more likely to need reverted to a snapshot etc...

**Comment by jtweed** [comment]
I think we may also need to create an identifier for every entity we ingest, so that we can consistently refer to them internally. We can't create valid JSON[-LD] without consistent identifiers. We'd then need the ID service to nominate one as canonical for de-duped entities.

**Comment by alexwlchan** [comment]
> I think we may also need to create an identifier for every entity we ingest, so that we can consistently refer to them internally

Each data source comes with its own identifiers (and some refer to each other) – my idea was that the alt identifiers would be lifted directly from the individual data sources.

The internally consistent identifier is then the one we mint ourselves, but don’t expose publicly.

**Comment by alexwlchan** [comment]
One clarification from a chat with @jtweed: we _are_ exposing our identifiers publicly, because we become the canonical source of truth.

**Comment by alexwlchan** [comment]
A few more notes from a conversation with @alfraser86 and @kenoir:

* Most of our services are designed with the assumption that we could rebuild them from the primary data sources if necessary. Because the contents of this database are history dependent and part of the public data set, we can’t change it after the fact.

  This means that Elasticsearch is probably out.

* To avoid race conditions, our ID minter has to be blocking. Otherwise we could allocate more than one canonical identifier for the same record, if it gets added to multiple data sources from quick succession. Once we’re blocking, we have to deal with queues and the like.

* The original idea of putting the ID minter in the transformer means we have ID minting logic in every transformer – lots of duplication. Do we need to do it that way?

Here’s part of our current architecture:

![ingest architecture 2-1a](https://cloud.githubusercontent.com/assets/301220/23903244/c2ab567a-08bb-11e7-85b2-01ffacb62481.png)

Now we’re thinking of adding a second queue, like so:

![ingest architecture 2-1b](https://cloud.githubusercontent.com/assets/301220/23903399/544f3240-08bc-11e7-9d1d-d2a147bdba1a.png)

The transformer pushes records to the SQS queue (via SNS), including all the known identifiers. The ID service plucks records off this queue, queries some data store (probably DynamoDB), and produces an identifier. It stamps that identifier into the record, then pushes it to a second queue, which is where the worker retrieves records for Elasticsearch ingest.

**Comment by alexwlchan** [comment]
And here’s another problem I thought of: what if we discover we have to merge two records after we’ve  minted them separate identifiers?

**Comment by jtweed** [comment]
That's not an if, that's guaranteed to happen. Which is why I think we need the idea of a picking one of those identifiers to represent the merged set as it exists in ES.

**Comment by alexwlchan** [comment]
**What do our identifiers look like?**

As discussed in backlog refinement:

* 8 characters
* Composed of digits and the Roman alphabet
* Case-insensitive (I lean towards printing as lowercase so the letters/numbers are easier to distinguish, FWIW)
* No check digit
* No ambiguous characters (which rules out `i/l/1` and `o/0`, I think, maybe `5/s` any others?)

**Comment by kenoir** [comment]
Something like:

```scala
import scala.util.Random

val r = Random
val forbiddenLetters = List("o","i","l")
val letterSet = ('a' -> 'z').filterNot(forbiddenLetters.contains)

(1 to 8).map(_ => letterSet(r.nextInt(letterSet.length))
```
