### ISSUE TITLE
Investigate removal of lambda triggers ...

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform-api#413]
... when lambdas are tainted and recreated.

**Comment by alexwlchan** [comment]
Having done a bit of digging: this only occurs with the CloudWatch based triggers.

I’d like to use `depends_on` so that the triggers can’t be created until after the Lambda is done, but it doesn’t seem like Terraform lets you do that.

* You can depend on an entire module being created…
* But the creation of a module can’t be dependent on anything.
* Nor can you inject a dependency into a module.

The triggers are updated when you re-run `terraform plan`. Next Q: what happens if we taint the trigger at the same time we taint the Lambda? 🤔

**Comment by alexwlchan** [comment]
> if we taint the trigger at the same time we taint the Lambda?

Nope, we still lose the trigger when we re-apply. :(

How would folks feel about having an `apply` wrapper script that detects if we need to re-plan and apply because the Lambdas got tainted? @alicefuzier @kenoir

**Comment by alexwlchan** [comment]
It’s still the case that re-running `plan` if you've changed the Lambda source code doesn't notice and trigger an update. Maybe trashing the auto-generated ZIP bundle…?

**Comment by alexwlchan** [comment]
Nope, trashing the ZIP bundles in such a way that their contents/checksums change doesn’t do it.
