### ISSUE TITLE
Convert Miro C images to TIFF

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#504]

**Comment by alexwlchan** [comment]
I did some quick analysis of the S3 bucket – apparently we have 4999 scanned images in the C collection. That sound right?

```python
import boto3

client = boto3.client('s3')

def get_matching_keys():
    token = None
    while True:
        kwargs = {
            'Bucket': BUCKET_NAME,
            'Prefix': PREFIX
        }
        if token is None:
            kwargs['ContinuationToken'] = token
        x = client.list_objects_v2(**kwargs)
        for img in x['Contents']:
            yield img['Key']
        try:
            token = x['NextContinuationToken']
        except KeyError:
            return

images = list(get_matching_keys())
print(len(images))
```

**Comment by alexwlchan** [comment]
When we copy these TIFFs to S3, use the standard infrequent access storage class.

**Comment by alexwlchan** [comment]
Ah, plus another 144k in the corporate photography folder. Okay then. :P

**Comment by alexwlchan** [comment]
This has been an exercise in edge cases, so a few notes on how it’s going:

* I started with a Python script that captured all the matching S3 keys (a modification of the above), and pushed them to an SQS queue.
* Then I wrote a bash script that polls the SQS queue, copies the image locally, converts it and pushes it to the new S3 bucket.
* Wrap this bash script in a container, run 100+ instances of it in ECS over the weekend, enjoy health benefits from not eating the takeaway pizza you could otherwise have bought with the cost of the EC2 instances.
* Wait four days.

About 146.5k were successfully processed off the SQS queue. Of the remaining 3.5k:

* It looks like ~3.4k were still processed, but sent to the DLQ before they were marked as done. We were right on the cusp of the 4-day timeout – I’d guess we hit a funny race condition where the DLQ processor and the bash scripts were getting the same queue entries.
* Nearly 75k images in the new bucket have a .JP2 extension. 🙈 I was only swapping .jp2 to .tif, and forgot about uppercase extensions.
* 36 images didn’t end up with a corresponding image in the new bucket. Of those, I see a mixture of:

  - Never seemed to be processed
  - JP2 processing errors:

    ```
    Kakadu Core Error:
    Illegal `Ckernels' value found while finalizing a COD/COC marker segment.
    Reversible processes must use the W5X3 kernel, while irreversible processes
    must use the W9X7 kernel, unless you have explicitly identified a different
    (Part-2) kernel, via the `Catk' attribute.
    ```

    ```
    Error in Kakadu File Format Support:
    JPX data source appears to contain no codestreams at all.
    ```

    I’ll grab those files and inspect them locally.
