### ISSUE TITLE
Create new-style shoots for corporate shoots in Miro

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#506]

**Comment by alexwlchan** [comment]
From my chat with @jtweed this afternoon: for starters, we want CSV files in S3, one for each shoot, with the following headings:

```
Title, Reference, Location, Staff Photog, Freelance Photog, Intended Usage, People
```

First draft of that script is here: https://github.com/wellcometrust/platform-private/pull/3

(Private for now because (1) it has a lot of MIRO-specific code in it, unlikely to be useful and (2) there are hard-coded references to individual shoots.)

**Comment by alexwlchan** [comment]
I looked at parsing the People field based on the MIRO data, but it’s pretty messy, so we’re going to ignore that for now.

**Comment by alexwlchan** [comment]
We now have a pile of per-shoot CSVs in S3, along with a single CSV with all of them for easy reference/review.

**Comment by alexwlchan** [comment]
I think this is done, subject to @jtweed reviewing the CSVs that have been created. Next step is using all of these to embed image-level metadata (#505).

**Comment by alexwlchan** [comment]
Closing as we have all the CSVs now.
